name: Azure Functions e ...

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: function-package
        path: dist

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: 'your-function-app-name'
        package: ${{ github.workspace }}/dist
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}